package com.eventplanner.model;

import java.sql.Timestamp;

public class Event {
    private int id;
    private int userId; // ID of the user who created it (if personal)
    private String title;
    private String description;
    private Timestamp dateTime;
    private String location;
    private String category;
    private String priority; // e.g., "High", "Medium", "Low"
    private Integer assignedGroupId; // Null if personal, Group ID if assigned by Admin
    private String createdBy; // Display name of creator (useful for group events)
    public void setAssignedGroupId(Integer assignedGroupId) {
        this.assignedGroupId = assignedGroupId;
    }

    // Constructor for creating NEW personal events (ID generated by DB)
    public Event(int userId, String title, String description, Timestamp dateTime, String location, String category, String priority) {
        this.userId = userId;
        this.title = title;
        this.description = description;
        this.dateTime = dateTime;
        this.location = location;
        this.category = category;
        this.priority = priority;
        this.assignedGroupId = null; // Personal event
    }

    // Constructor for loading events FROM DB (includes ID and potentially group info)
    public Event(int id, int userId, String title, String description, Timestamp dateTime, String location, String category, String priority, Integer assignedGroupId, String createdBy) {
        this.id = id;
        this.userId = userId;
        this.title = title;
        this.description = description;
        this.dateTime = dateTime;
        this.location = location;
        this.category = category;
        this.priority = priority;
        this.assignedGroupId = assignedGroupId;
        this.createdBy = createdBy;
    }


    // --- Getters ---
    public int getId() { return id; }
    public int getUserId() { return userId; } // Creator's ID
    public String getTitle() { return title; }
    public String getDescription() { return description; }
    public Timestamp getDateTime() { return dateTime; }
    public String getLocation() { return location; }
    public String getCategory() { return category; }
    public String getPriority() { return priority; }
    public Integer getAssignedGroupId() { return assignedGroupId; }
    public String getCreatedBy() { return createdBy; }
    public boolean isPersonal() { return assignedGroupId == null; }


    // --- Setters (mainly for editing) ---
    public void setId(int id) { this.id = id; }
    public void setTitle(String title) { this.title = title; }
    public void setDescription(String description) { this.description = description; }
    public void setDateTime(Timestamp dateTime) { this.dateTime = dateTime; }
    public void setLocation(String location) { this.location = location; }
    public void setCategory(String category) { this.category = category; }
    public void setPriority(String priority) { this.priority = priority; }
    // assignedGroupId is usually set on creation by admin, not edited by user
    // userId is set on creation

    @Override
    public String toString() {
        return title + " (" + (isPersonal() ? "Personal" : "Group") + ") - " + dateTime;
    }
}